### ISSUE TITLE
millisecond timestamps

### ISSUE THREAD

**Issue by jpuskar** [c-icap/c-icap-server#2]
Greetings.
Would it be possible to support millisecond resolution timestamps in the logs? Similar to squid's `"%ts.%tu"` log format.

**Comment by chtsanti** [comment]
commit 9f2c9d71

It modifies the %ts log format code to accept as parameter ms or microseconds precision: "%{m}ts" will print something like the "1609955255.282"  and the "%{u}ts" will print something like the "1609955255.282185".

This is will included to the next c-icap major release (0.6.x release)
