### ISSUE TITLE
What are the system requirements to setup in Windows?

### ISSUE THREAD

**Issue by bobsag** [c-icap/c-icap-server#29]
Hi @chtsanti, @tomers , @treveradams  @mkauf

I'm trying to setup an ICAP server for scanning files, so I wanted to know if it's possible to set it up on Windows?
If not, for Linux, what are the pre-requisites required so that I'll be able to scan files?

Thank you.

**Comment by chtsanti** [comment]
MS windows are not supported by c-icap server.
You may be able to compile and run under cygwin the development c-icap version from git master branch.

To use clamav to scan for virus, you need to download the latest c-icap release AND the latest c-icap-modules package.
Prerequisites to compile these two packages are a gcc or clang compiler the zlib-dev, the brotli-dev (optional), the Berkeley Database libraries (optional)  and the libclamav-dev packages.

**Comment by bobsag** [comment]
Thanks for the help @chtsanti !!!
