### ISSUE TITLE
Support for multipart messages

### ISSUE THREAD

**Issue by kravietz** [c-icap/c-icap-server#3]
I would like to suggest an improvement to the c-icap-server code: support MIME multipart messages. This is quite frequent to receive messages such as the following one when scanning file upload traffic etc - unfortunately, when this is sent to ClamAV, it will not detect the EICAR vector since file type detection will *not* indicate an executable file (even if the executable is hidden inside).

```
--multipart-boundary
Content-Disposition: form-data; name="photo"; filename="infected.jpg"
Content-Type: text/plain

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
--multipart-boundary--
```
I can think of two options to mitigate this:
* Loop over the parts and send each of them to ClamAV separately
* Detect a multipart message (it will have `Content-Type: multipart/form-data`) and then use a simple trick  -- prepend a `From` and `Content-Type` headers to make it look like a MIME email, in which case ClamAV will loop over the parts and scan them as separate files. The contents of `From` header are not really important.

```
From: sender@example.com
Content-Type: multipart/form-data; boundary="multipart-boundary"

--multipart-boundary
Content-Disposition: form-data; name="photo"; filename="infected.jpg"
Content-Type: text/plain

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
--multipart-boundary--
```
I can implement the feature and submit a MR, just wanted to discuss the best approach first.

**Comment by kravietz** [comment]
It's now resolved in [squidclamav](https://github.com/darold/squidclamav/pull/46).

**Comment by asterite3** [comment]
It seems it does not work for binary files because ClamAV [reads mail line-by-line](https://github.com/Cisco-Talos/clamav/blob/11b069d/libclamav/mbox.c#L1102), and [skips NULL bytes when doing so](https://github.com/Cisco-Talos/clamav/blob/11b069d/libclamav/mbox.c#L4022).
Made an squidclamav issue about it here https://github.com/darold/squidclamav/issues/58
