### ISSUE TITLE
Question: max URL length

### ISSUE THREAD

**Issue by tomers** [c-icap/c-icap-server#39]
Hello, is there any limitation on the URL length in c-icap?

**Comment by chtsanti** [comment]
HTTP url or ICAP url?
There is not any limit in HTTP URL size.
There is limit in practice for ICAP url,  because of the ICAP service name length and service arguments size.

**Comment by tomers** [comment]
Thanks, Christos.

I meant HTTP URL size.

**Comment by chtsanti** [comment]
Just note about the ci_http_request_url function. This function does not return the URL arguments.
At the master branch there is the ci_http_request_url2 function which, if used with the CI_HTTP_REQUEST_URL_ARGS flag includes also the url arguments.

**Comment by egberts** [comment]
Did you find the answe?
