### ISSUE TITLE
Small issues when building on Fedora/EPEL

### ISSUE THREAD

**Issue by scaronni** [c-icap/c-icap-server#49]
A couple of small issues when checking the resulting build on Fedora/EPEL:

`/usr/lib64/libcicap.so.0.0.0` - The library is not dynamically linked against libc`.

`/usr/include/c_icap/txtTemplate.h` - The Free Software Foundation address in this file seems to be outdated or misspelled.

`/usr/sbin/c-icap` - The binary calls gethostbyname. Please port the code to use getaddrinfo.

Thanks!

**Comment by chtsanti** [comment]
Please try to use latest c-icap master branch if you like.
The issues should have been resolved.

**Comment by scaronni** [comment]
Thanks, they have all been fixed!
