### ISSUE TITLE
Link with sourceforge project and 0.5.6 release

### ISSUE THREAD

**Issue by ffontaine** [c-icap/c-icap-server#5]
What is the link between this repo and https://sourceforge.net/p/c-icap/code/HEAD/tree/c-icap-server? Does this one is the official upstream repo? If this the official repo, could we get a github tag for 0.5.6 that has been released on sourceforge?

**Comment by chtsanti** [comment]
The official repository now is the git repository in github.
The svn repository is not updated, or not updated  regularly.

**Comment by ffontaine** [comment]
Thanks for your answer then would it possible to add a github release for 0.5.6 that has been released on sourceforge (https://sourceforge.net/projects/c-icap/files/c-icap/0.5.x/c_icap-0.5.6.tar.gz/download)? The latest github release is 0.5.5

**Comment by chtsanti** [comment]
Done.
Thank you!

**Comment by ffontaine** [comment]
Thanks
