### ISSUE TITLE
atomic.c fails to build on RHEL7

### ISSUE THREAD

**Issue by frankcrawford** [c-icap/c-icap-server#53]
The latest version of `atomic.c` fails to compile on RHEL7, as RHEL7 does not have `c11 atomic` available (i.e. `__CI_INLINE_POSIX_ATOMICS` is not set), so the macro definition for `_implement_atomic_ops(name, type)` is invalid, as it is missing a `\` at line 101.

The actual error is:
```
atomic.c: At top level:
atomic.c:102:25: error: stray '##' in program
     void ci_atomic_load_##name ## _gl(const type *counter, type *store) { \
                         ^
atomic.c:102:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'name'
     void ci_atomic_load_##name ## _gl(const type *counter, type *store) { \
                           ^
atomic.c:102:32: error: stray '##' in program
     void ci_atomic_load_##name ## _gl(const type *counter, type *store) { \
                                ^
```
plus additional errors for following lines.

**Comment by chtsanti** [comment]
This is should fixed in latest c-icap master branch

**Comment by scaronni** [comment]
Works fine, thank you! @frankcrawford  you can close the ticket, the build was succesful in koji.

**Comment by frankcrawford** [comment]
Done.  The build error for rawhide looks like a koji problem, but not an issue for this repo.
